spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:user-db}
    username: ${DB_USER:my_user}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: ${APP_PORT:8080}
