
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/vacancy-db
    username: my_user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8081
