version: '3.8'

services:
  postgres:
    image: postgres
    container_name: user-ms
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-db
    ports:
      - "5435:5432"
    volumes:
      - yenidb_1:/var/lib/postgresql/data
    networks:
      my_network_1:


networks:
  my_network_1:

volumes:
  yenidb_1:
